backend:
  name: github
  branch: main
  repo: 2312ATC/2312atc
  base_url: https://decap.tavistock.air-cadets.org
  auth_endpoint: /auth

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Featured Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "landingCarousel"
    label: "Landing Carousel"
    folder: "src/content/landingCarousel"
    create: true
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string", required: false, hint: "Optional link to the image", pattern: ["\/[a-zA-Z0-9_\/]+", "must start with a slash"] }

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "../../assets/images" # The src attribute for uploaded media